[tool]
[tool.poetry]
description = "FCC ISP Port Scanner Project"
authors = ["Jeremy A Gray <jeremy.a.gray@gmail.com>"]
name = "fcc-isp-port-scanner"
version = "0.0.1"
[tool.poetry.dependencies]
python = "^3.8"
[tool.poetry.dev-dependencies]
pytest = "*"
pytest-flakes = "*"
pytest-flake8 = "*"
